### ISSUE TITLE
Licensing is unclear in src/jane_asttypes.mli

### ISSUE THREAD

**Issue by SnarkBoojum** [janestreet/ppxlib_jane#1]
The header for this file says it's LGPL-2.1 with an exception mentioned in LICENSE. But only LICENSE.md exists and it doesn't contain anything about an exception.

**Comment by dkalinichenko-js** [comment]
Hi! This file is copied from the [flambda-backend](https://github.com/ocaml-flambda/flambda-backend) repository, and the license it mentions is the [OCaml Compiler license](https://github.com/ocaml-flambda/flambda-backend/blob/main/ocaml/LICENSE).

**Comment by ncik-roberts** [comment]
Incidentally, that file will be removed in the next release.

**Comment by ncik-roberts** [comment]
The file has been deleted.
