### ISSUE TITLE
Location.errorf printers expect Format_doc formatter but existing pretty printers come from Format

### ISSUE THREAD

**Issue by wokalski** [janestreet/ppxlib_jane#3]
I was compiling ppxlib_jane against ocaml 5.3 with the latest ppxlib and it didn't compile because of the discrepancies in the formatting types.

I don't know what's the correct solution (I ended up hacking around it quickly). Here's some related discussion
https://github.com/ocaml-ppx/ppxlib/pull/487. I've also seen `Format_doc.deprecated_printer` which I believe built for this.

**Comment by dkalinichenko-js** [comment]
Fixed in `v0.17.2`.
